<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\myshop.DAL\myshop.DAL.csproj" />
  </ItemGroup>

  <Target Name="ResetFilesPropertyAndItems" BeforeTargets="BeforeBuild;Build;PrepareForBuild;Restore;GetCopyToOutputDirectoryItems;DefineStaticWebAssets;GenerateStaticWebAssetsManifest;AssignTargetPaths">
    <PropertyGroup>
      <Files></Files>
    </PropertyGroup>
    <ItemGroup>
      <Files Remove="@(Files)" />
    </ItemGroup>
  </Target>

</Project>
